embeddings {
  tensor_name: "default:00414"
  metadata_path: "00414/default/metadata.tsv"
  sprite {
    image_path: "00414/default/sprite.png"
    single_image_dim: 224
    single_image_dim: 224
  }
  tensor_path: "00414/default/tensors.tsv"
}
embeddings {
  tensor_name: "default:00621"
  metadata_path: "00621/default/metadata.tsv"
  sprite {
    image_path: "00621/default/sprite.png"
    single_image_dim: 224
    single_image_dim: 224
  }
  tensor_path: "00621/default/tensors.tsv"
}
